version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: cooklist_api
      dockerfile: ./compose/local/Dockerfile
    image: connect_backend_local_django
    container_name: cooklist_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: cooklist_api
      dockerfile: ./compose/production/postgres/Dockerfile
    image: connect_backend_production_postgres
    container_name: cooklist_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    ports:
      - ${POSTGRES_EXPOSE_PORT:-5432}:5432
    env_file:
      - ./.env