# Generated by Django 4.0 on 2022-01-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduledrecipe",
            old_name="date_planned",
            new_name="date_scheduled",
        ),
    ]
