# Generated by Django 3.2.5 on 2022-01-02 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledrecipe',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
